### ISSUE TITLE
functions.php

### ISSUE THREAD

**Issue by MarcGaumont** [mguery/base-theme#1]
wp_enqueue_style( 'google-fonts', 'fonts.googleapis.com/css?family=Montserrat|Noto+Serif' );

SHOULD BE 

wp_enqueue_style( 'google-fonts', '//fonts.googleapis.com/css?family=Montserrat|Noto+Serif' );

Fonts don't load without the // ... the site url is tagged on and the fonts never load, + console errors

**Comment by mguery** [comment]
@MarcGaumont thank you! I just updated it.
